// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.Data;
using Moq;
using BloodBankManagementSystem;

namespace BloodBankManagementSystem.Test
{
    [TestFixture]
    public class frmHome_txtSearch_TextChanged_e5ba9dfd61_Test
    {
        private Mock<IDataAccessLayer> _mockDal;
        private frmHome _frmHome;

        [SetUp]
        public void SetUp()
        {
            _mockDal = new Mock<IDataAccessLayer>();
            _frmHome = new frmHome(_mockDal.Object);
        }

        [Test]
        public void txtSearch_TextChanged_KeywordsNotNull_DonorsFilteredBasedOnKeywords()
        {
            // Arrange
            var keywords = "test";
            var dataTable = new DataTable();
            _mockDal.Setup(x => x.Search(keywords)).Returns(dataTable);

            // Act
            _frmHome.txtSearch_TextChanged(this, new EventArgs());

            // Assert
            Assert.AreEqual(dataTable, _frmHome.dgvDonors.DataSource);
        }

        [Test]
        public void txtSearch_TextChanged_KeywordsNull_AllDonorsDisplayed()
        {
            // Arrange
            var dataTable = new DataTable();
            _mockDal.Setup(x => x.Select()).Returns(dataTable);

            // Act
            _frmHome.txtSearch_TextChanged(this, new EventArgs());

            // Assert
            Assert.AreEqual(dataTable, _frmHome.dgvDonors.DataSource);
        }

        [TearDown]
        public void TearDown()
        {
            _mockDal = null;
            _frmHome = null;
        }
    }
}
