// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System.Windows.Forms;
// Ensure that the BloodBankManagementSystem.UI and frmDonors namespaces are correctly referenced
using BloodBankManagementSystem.UI;
using BloodBankManagementSystem.UI.frmDonors;

namespace BloodBankManagementSystem.UI.Test
{
    [TestFixture]
    public class frmDonors_frmDonors_1ab0055eaf
    {
        private frmDonors _frmDonors;

        [SetUp]
        public void SetUp()
        {
            _frmDonors = new frmDonors();
        }

        [Test]
        public void frmDonors_Creation_NotNull()
        {
            Assert.IsNotNull(_frmDonors);
        }

        [Test]
        public void frmDonors_Creation_IsInstanceOfType()
        {
            Assert.IsInstanceOf(typeof(Form), _frmDonors);
        }
    }
}
