// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using System;
using System.IO;
using NUnit.Framework;
using Moq;
using System.Windows.Forms;

namespace BloodBankManagementSystem.UI.Test
{
    [TestFixture]
    public class frmDonors_btnSelectImage_Click_1f124cdff5
    {
        private Mock<OpenFileDialog> _openFileDialogMock;
        private Mock<PictureBox> _pictureBoxMock;
        private string _applicationPath;

        [SetUp]
        public void Setup()
        {
            _openFileDialogMock = new Mock<OpenFileDialog>();
            _pictureBoxMock = new Mock<PictureBox>();
            _applicationPath = AppDomain.CurrentDomain.BaseDirectory;
        }

        [Test]
        public void Test_SelectImage_Click_ImageSelectedAndExists()
        {
            // Arrange
            _openFileDialogMock.Setup(o => o.ShowDialog()).Returns(DialogResult.OK);
            _openFileDialogMock.Setup(o => o.CheckFileExists).Returns(true);

            // Act
            btnSelectImage_Click(null, null);

            // Assert
            _openFileDialogMock.Verify(o => o.ShowDialog(), Times.Once);
            _pictureBoxMock.Verify(p => p.Image, Times.Once);
            Assert.AreEqual("Blood_Bank_MS_" + name + g + ext, imageName);
            Assert.AreEqual(_applicationPath.Substring(0, _applicationPath.Length - 10) + "\\images\\" + imageName, destinationPath);
        }

        [Test]
        public void Test_SelectImage_Click_ImageNotSelected()
        {
            // Arrange
            _openFileDialogMock.Setup(o => o.ShowDialog()).Returns(DialogResult.Cancel);

            // Act
            btnSelectImage_Click(null, null);

            // Assert
            _openFileDialogMock.Verify(o => o.ShowDialog(), Times.Once);
            _pictureBoxMock.Verify(p => p.Image, Times.Never);
        }

        [Test]
        public void Test_SelectImage_Click_ImageSelectedButNotExists()
        {
            // Arrange
            _openFileDialogMock.Setup(o => o.ShowDialog()).Returns(DialogResult.OK);
            _openFileDialogMock.Setup(o => o.CheckFileExists).Returns(false);

            // Act
            btnSelectImage_Click(null, null);

            // Assert
            _openFileDialogMock.Verify(o => o.ShowDialog(), Times.Once);
            _pictureBoxMock.Verify(p => p.Image, Times.Never);
        }
    }
}
