// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using System;
using NUnit.Framework;
using Moq;
using System.Windows.Forms;
using BloodBankManagementSystem.UI; // Add the namespace where frmDonors class is defined.

[TestFixture]
public class frmDonors_dgvDonors_RowHeaderMouseClick_33d2aab8f3
{
    private frmDonors _frmDonors;
    private DataGridView _dataGridView;

    [SetUp]
    public void Setup()
    {
        _frmDonors = new frmDonors();
        _dataGridView = new DataGridView();
        _dataGridView.Columns.Add("ID", "ID");
        _dataGridView.Columns.Add("FirstName", "FirstName");
        _dataGridView.Columns.Add("LastName", "LastName");
        _dataGridView.Columns.Add("Email", "Email");
        _dataGridView.Columns.Add("Contact", "Contact");
        _dataGridView.Columns.Add("Gender", "Gender");
        _dataGridView.Columns.Add("Address", "Address");
        _dataGridView.Columns.Add("BloodGroup", "BloodGroup");
        _dataGridView.Columns.Add("ImageName", "ImageName");
        _dataGridView.Rows.Add("1", "Test", "User", "test@test.com", "1234567890", "Male", "123 Test St", "A+", "test.jpg");
    }

    [Test]
    public void dgvDonors_RowHeaderMouseClick_RowSelected_PopulatesFields()
    {
        // Arrange
        var e = new DataGridViewCellMouseEventArgs(0, 0, 0, 0, new MouseEventArgs(MouseButtons.Left, 1, 0, 0, 0));

        // Act
        _frmDonors.dgvDonors_RowHeaderMouseClick(_dataGridView, e);

        // Assert
        Assert.AreEqual("1", _frmDonors.txtDonorID.Text);
        Assert.AreEqual("Test", _frmDonors.txtFirstName.Text);
        Assert.AreEqual("User", _frmDonors.txtLastName.Text);
        Assert.AreEqual("test@test.com", _frmDonors.txtEmail.Text);
        Assert.AreEqual("1234567890", _frmDonors.txtContact.Text);
        Assert.AreEqual("Male", _frmDonors.cmbGender.Text);
        Assert.AreEqual("123 Test St", _frmDonors.txtAddress.Text);
        Assert.AreEqual("A+", _frmDonors.cmbBloodGroup.Text);
        Assert.AreEqual("test.jpg", _frmDonors.imageName);
    }

    [Test]
    public void dgvDonors_RowHeaderMouseClick_RowNotSelected_DoesNotPopulateFields()
    {
        // Arrange
        var e = new DataGridViewCellMouseEventArgs(0, -1, 0, 0, new MouseEventArgs(MouseButtons.Left, 1, 0, 0, 0));

        // Act
        _frmDonors.dgvDonors_RowHeaderMouseClick(_dataGridView, e);

        // Assert
        Assert.AreEqual("", _frmDonors.txtDonorID.Text);
        Assert.AreEqual("", _frmDonors.txtFirstName.Text);
        Assert.AreEqual("", _frmDonors.txtLastName.Text);
        Assert.AreEqual("", _frmDonors.txtEmail.Text);
        Assert.AreEqual("", _frmDonors.txtContact.Text);
        Assert.AreEqual("", _frmDonors.cmbGender.Text);
        Assert.AreEqual("", _frmDonors.txtAddress.Text);
        Assert.AreEqual("", _frmDonors.cmbBloodGroup.Text);
        Assert.AreEqual("", _frmDonors.imageName);
    }
}
