// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.Drawing;

namespace BloodBankManagementSystem.UI.Test
{
    [TestFixture]
    public class frmDonors_Clear_15d01529c9
    {
        private frmDonors form;
        private string defaultImagePath;

        [SetUp]
        public void Setup()
        {
            form = new frmDonors();
            defaultImagePath = AppDomain.CurrentDomain.BaseDirectory + "\\images\\no-image.jpg";
        }

        [Test]
        public void Clear_AllTextBoxesClearedAndDefaultImageSet()
        {
            // Arrange
            form.txtFirstName.Text = "Test";
            form.txtLastName.Text = "Test";
            form.txtEmail.Text = "Test";
            form.txtDonorID.Text = "Test";
            form.cmbGender.Text = "Test";
            form.cmbBloodGroup.Text = "Test";
            form.txtContact.Text = "Test";
            form.txtAddress.Text = "Test";
            form.imageName = "Test";
            form.pictureBoxProfilePicture.Image = new Bitmap(defaultImagePath);

            // Act
            form.Clear();

            // Assert
            Assert.IsEmpty(form.txtFirstName.Text);
            Assert.IsEmpty(form.txtLastName.Text);
            Assert.IsEmpty(form.txtEmail.Text);
            Assert.IsEmpty(form.txtDonorID.Text);
            Assert.IsEmpty(form.cmbGender.Text);
            Assert.IsEmpty(form.cmbBloodGroup.Text);
            Assert.IsEmpty(form.txtContact.Text);
            Assert.IsEmpty(form.txtAddress.Text);
            Assert.AreEqual("no-image.jpg", form.imageName);
            Assert.AreEqual(defaultImagePath, ((Bitmap)form.pictureBoxProfilePicture.Image).Tag.ToString());
        }

        [Test]
        public void Clear_WhenAlreadyCleared_NoChange()
        {
            // Arrange
            form.Clear();

            // Act
            form.Clear();

            // Assert
            Assert.IsEmpty(form.txtFirstName.Text);
            Assert.IsEmpty(form.txtLastName.Text);
            Assert.IsEmpty(form.txtEmail.Text);
            Assert.IsEmpty(form.txtDonorID.Text);
            Assert.IsEmpty(form.cmbGender.Text);
            Assert.IsEmpty(form.cmbBloodGroup.Text);
            Assert.IsEmpty(form.txtContact.Text);
            Assert.IsEmpty(form.txtAddress.Text);
            Assert.AreEqual("no-image.jpg", form.imageName);
            Assert.AreEqual(defaultImagePath, ((Bitmap)form.pictureBoxProfilePicture.Image).Tag.ToString());
        }

        [TearDown]
        public void TearDown()
        {
            form.Dispose();
        }
    }
}
