// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.Data;
using System.Drawing;
using Moq;
using BloodBankManagementSystem.UI.Test;
using System.Drawing.Common; //Added this namespace to resolve the Bitmap issue
using System.Windows.Forms; //Added this namespace to resolve the Forms issue

namespace BloodBankManagementSystem.UI.Test
{
    [TestFixture]
    public class frmDonors_frmDonors_Load_09749fa9fa
    {
        private Mock<IDonorsDal> _mockDal;
        private frmDonors _frmDonors;
        private DataTable _dt;
        private Bitmap _bitmap;

        [SetUp]
        public void Setup()
        {
            // Arrange
            _mockDal = new Mock<IDonorsDal>();
            _frmDonors = new frmDonors(_mockDal.Object);
            _dt = new DataTable();
            _bitmap = new Bitmap(1, 1);

            _mockDal.Setup(dal => dal.Select()).Returns(_dt);
            Application.StartupPath = "C:\\TestPath";
        }

        [Test]
        public void frmDonors_Load_DataSourceIsSetToDataTableFromDal()
        {
            // Act
            _frmDonors.frmDonors_Load(null, EventArgs.Empty);

            // Assert
            Assert.AreEqual(_dt, _frmDonors.dgvDonors.DataSource);
        }

        [Test]
        public void frmDonors_Load_ImageIsSetToNoImageBitmap()
        {
            // Arrange
            string imagePath = Application.StartupPath.Substring(0, (Application.StartupPath.Length) - 10) + "\\images\\no-image.jpg";
            _frmDonors.pictureBoxProfilePicture.Image = _bitmap;

            // Act
            _frmDonors.frmDonors_Load(null, EventArgs.Empty);

            // Assert
            Assert.AreEqual(_bitmap, _frmDonors.pictureBoxProfilePicture.Image);
        }

        [TearDown]
        public void Teardown()
        {
            _frmDonors.Dispose();
            _bitmap.Dispose();
        }
    }
}
