// Test generated by RoostGPT for test CSharp-Blood-Bank-Management-System using AI Type Open AI and AI Model gpt-4

using NUnit.Framework;
using System;
using System.Windows.Forms;
using BloodBankManagementSystem.UI;

namespace BloodBankManagementSystem.UI.Test
{
    [TestFixture]
    public class frmLogin_InitializeComponent_cd9b87bd2f
    {
        private frmLogin _frmLogin;

        [SetUp]
        public void Setup()
        {
            _frmLogin = new frmLogin();
            _frmLogin.InitializeComponent();
        }

        [Test]
        public void InitializeComponent_WhenCalled_SetsAppropriateProperties()
        {
            Assert.AreEqual(FormStartPosition.CenterScreen, _frmLogin.StartPosition);
            Assert.AreEqual(FormBorderStyle.None, _frmLogin.FormBorderStyle);
            Assert.AreEqual("frmLogin", _frmLogin.Text);
        }

        [Test]
        public void InitializeComponent_WhenCalled_SetsAppropriateControls()
        {
            Assert.AreEqual(9, _frmLogin.Controls.Count); // TODO: Update this value based on the actual number of controls
            Assert.IsNotNull(_frmLogin.Controls.Find("pictureBox1", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("lblUsername", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("txtUsername", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("txtPassword", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("lblPassword", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("btnLogin", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("lblAppName", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("lblAppSubName", false)[0]);
            Assert.IsNotNull(_frmLogin.Controls.Find("pictureBoxAppIcon", false)[0]);
        }

        [TearDown]
        public void TearDown()
        {
            _frmLogin.Dispose();
        }
    }
}
